import Script from "next/script";
import Link from "next/link";
import {APP_URL,CTA,FAQList,Footer,Header,Phone,StoreButtons,asset,faqItems} from "./components";

export default function Home() {
 const schema={"@context":"https://schema.org","@graph":[{"@type":"Organization","@id":"#org","name":"K53 Fast","url":"/"},{"@type":"WebSite","@id":"#website","name":"K53 Fast","url":"/","publisher":{"@id":"#org"}},{"@type":"SoftwareApplication","name":"K53 Fast","applicationCategory":"EducationalApplication","operatingSystem":"Web, iOS, Android","url":APP_URL,"description":"K53 learner's licence practice app for South Africa with road rules, road signs, vehicle controls and mock tests.","offers":{"@type":"Offer","price":"0","priceCurrency":"ZAR"}},{"@type":"FAQPage","mainEntity":faqItems.slice(0,4).map(([q,a])=>({"@type":"Question","name":q,"acceptedAnswer":{"@type":"Answer","text":a}}))}]};
 return <><Header/><main id="main"><section className="hero"><div className="road-line one"/><div className="road-line two"/><div className="shell hero-grid"><div className="hero-copy"><div className="kicker"><span>🇿🇦</span> Made for SA learner drivers</div><h1>Pass your K53<br/>with <em>confidence.</em></h1><p className="hero-lede">1,574 real practice questions. Image-based road signs. Smart drills that focus on your weak spots. One seriously good way to get test-ready.</p><div className="hero-actions"><a className="button" href={APP_URL}>Start practising free ↗</a><a className="text-link" href="#how">See how it works ↓</a></div><div className="trust-row"><span>✓ No download needed</span><span>✓ Code A, B &amp; C</span><span>✓ Mobile-first</span></div></div><div className="hero-visual" aria-label="K53 Fast app screens"><span className="sticker sticker-lime">1,574<br/><small>QUESTIONS</small></span><span className="sticker sticker-coral">LET'S<br/>GO!</span><Phone screen="/app-screens/practice.png" alt="K53 Fast practice topic screen" tilt="tilt-left"/><Phone screen="/app-screens/mock-test.png" alt="K53 Fast mock test screen" tilt="tilt-right"/><div className="float-sign"><img src={asset("/signs/two-way-traffic.webp")} alt="Two-way traffic warning sign" width="512" height="512"/></div></div></div></section>

 <section className="ticker" aria-label="App highlights"><div>ROAD RULES <b>✦</b> ROAD SIGNS <b>✦</b> VEHICLE CONTROLS <b>✦</b> MOCK TESTS <b>✦</b> SMART PRACTICE <b>✦</b> CODE A · B · C <b>✦</b></div></section>

 <section className="stats"><div className="shell stat-grid"><div><strong>1,574</strong><span>practice questions</span></div><div><strong>172</strong><span>image-based questions</span></div><div><strong>3</strong><span>vehicle codes covered</span></div><div><strong>24/7</strong><span>practice in your pocket</span></div></div></section>

 <section className="section" id="how"><div className="shell"><div className="section-head"><div><span className="eyebrow">HOW IT WORKS</span><h2>Less panic.<br/>More progress.</h2></div><p>Short, focused practice that actually tells you where to improve—without the dusty textbook energy.</p></div><div className="steps"><article className="step blue"><span>01</span><div className="icon-block">☝</div><h3>Pick your lane</h3><p>Choose road rules, road signs, vehicle controls or a mixed practice session.</p></article><article className="step coral"><span>02</span><div className="icon-block">⚡</div><h3>Build the streak</h3><p>Answer quick drills, bookmark tricky questions and review every mistake.</p></article><article className="step lime"><span>03</span><div className="icon-block">🏁</div><h3>Own the mock</h3><p>Switch to timed exam conditions and watch your readiness grow.</p></article></div></div></section>

 <section className="section signs-section"><div className="shell signs-grid"><div><span className="eyebrow">SIGNS, WITHOUT THE SHRUG</span><h2>See it.<br/>Know it.<br/><em>Move.</em></h2><p>Road signs are easier to remember when you practise with the actual visuals. K53 Fast includes square, sign-focused images built for small screens.</p><Link className="text-link light" href="/k53-road-signs">Explore K53 road signs →</Link></div><div className="sign-cards"><figure><img src={asset("/signs/railway-warning.webp")} alt="Railway crossing warning sign" width="512" height="512"/><figcaption>Warning signs</figcaption></figure><figure><img src={asset("/signs/dead-end.webp")} alt="Dead end road sign" width="512" height="512"/><figcaption>Information signs</figcaption></figure><figure><img src={asset("/signs/loose-stones.webp")} alt="Loose stones warning sign" width="512" height="512"/><figcaption>Hazard signs</figcaption></figure></div></div></section>

 <section className="section app-tour"><div className="shell tour-grid"><div className="tour-phone"><Phone screen="/app-screens/practice.png" alt="K53 Fast smart practice modes"/><span className="bubble bubble-one">Weak areas? →<br/><b>Drill them.</b></span><span className="bubble bubble-two">Mistakes? →<br/><b>Review them.</b></span></div><div><span className="eyebrow">BUILT AROUND YOU</span><h2>Your practice. Your pace. Your comeback.</h2><ul className="feature-list"><li><b>Topic practice</b><span>Focus on one K53 section at a time.</span></li><li><b>Smart weak-area drills</b><span>Spend more time where your score needs it.</span></li><li><b>Mock tests</b><span>Practise with timed exam pressure.</span></li><li><b>Progress tracking</b><span>See your accuracy, streak and readiness.</span></li></ul><a className="button" href={APP_URL}>Try the app free ↗</a></div></div></section>

 <section className="section download" id="download"><div className="shell download-card"><div><span className="eyebrow">YOUR NEXT MOVE</span><h2>Practise now.<br/>Download soon.</h2><p>The mobile web app is live today. App Store and Google Play versions are on the way—no fake buttons, no broken promises.</p><StoreButtons/></div><div className="download-art"><div className="qr-fake" aria-hidden="true"><span>▦</span><small>OPEN WEB APP</small></div><span className="scribble">SCAN<br/>ME ↙</span></div></div></section>

 <section className="section faq-home"><div className="shell faq-grid"><div><span className="eyebrow">QUICK ANSWERS</span><h2>Before you ask...</h2><p>Everything you need to know before you tap start.</p><Link className="text-link" href="/faq">View all FAQs →</Link></div><FAQList limit={4}/></div></section><CTA/></main><Footer/><Script id="schema" type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></>;
}
